name: tomato_scfs
description: 毕业设计、家校通.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.15.7
  scoped_model: ^1.0.1
  rxdart: ^0.21.0
  dio: ^2.1.2
  bloc: ^0.11.2
  http: ^0.12.0+2
  flutter_swiper: ^1.1.6
  flutter_webview_plugin: ^0.3.3
  shared_preferences: ^0.5.2
  fluttertoast: ^3.0.3
  event_bus: ^1.1.0
  flutter_slidable: ^0.4.9
  # 汉字转拼音库 https://github.com/flutterchina/lpinyin
  lpinyin: ^1.0.7
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.1.0
  flutter_screenutil: ^0.5.1
  intro_slider: ^1.2.0
  share: ^0.6.1
  # 查看图片
  photo_view: ^0.2.4
  # 数据
  sqflite: ^1.1.5
  # 文件读写
  path_provider: ^0.5.0+1
  marquee_flutter: ^0.1.3
#  firebase_auth: ^0.8.4+5
#  google_sign_in: ^4.0.1+3
#  cloud_firestore: ^0.9.13+1
  image_picker:  ^0.5.4
#  firebase_storage: ^2.1.0+1
  cached_network_image: ^0.7.0
  # 国际化
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^8.4.0



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    #加载页面图片资源
    - assets/images/loading.png
    - assets/images/flutter.png
    - assets/images/head.jpg
    - assets/images/arrow_right.png
    - assets/images/ic_error.png
    - assets/images/ic_empty.png
    - assets/images/full-bloom.png
    - assets/images/mountains.jpeg
    - assets/images/mountains.jpg
    - assets/images/logo.png
    - assets/images/alucard.jpg
    - assets/images/img_not_available.jpeg
    - assets/images/mimi1.gif
    - assets/images/mimi2.gif
    - assets/images/mimi3.gif
    - assets/images/mimi4.gif
    - assets/images/mimi5.gif
    - assets/images/mimi6.gif
    - assets/images/mimi7.gif
    - assets/images/mimi8.gif
    - assets/images/mimi9.gif

  fonts:
  - family: icomoon
    fonts:
      - asset: assets/fonts/IcoMoon.ttf
  - family: Nunito
    fonts:
      - asset: assets/fonts/Nunito.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
